spectaql:
  logoFile: ./logo/logo.svg
  faviconFile: ./logo/logo.svg
  displayAllServers: true

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ./src/schema.gql
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: ANS directory api
  description: Made with ❤️ by MonOrdo
  termsOfService: https://www.monordo.com
  contact:
    name: API Support
    url: https://www.monordo.com
    email: axel@monordo.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-introItems:
    - title: Access
      description: Ask us if you want an api key

servers:
  - url: https://ans.monordo.com/graphql
    description: Production
    production: true
    headers:
      - name: api-key
        example: <YOUT_API_KEY>
        comment: Request you api key from the support team